use crate::brush_engine::brush::Brush;
use crate::brush_engine::stabilizer::Stabilizer;
use crate::canvas::Canvas;
use crate::canvas::history::UndoAction;
use crate::selection::SelectionManager;
use eframe::egui::Color32;
use eframe::egui::Vec2;
use rand::Rng;
use rayon::ThreadPool;
use rustc_hash::FxHashMap;
use std::collections::HashSet;
use std::sync::Mutex;

/// Per-tile state for indirect painting (Krita's temporary stroke device):
/// dabs only accumulate `coverage`, and the tile's pixels are re-resolved from
/// `original` (the tile as it was when the stroke first touched it) plus the
/// coverage. Pixels are never re-quantized to 8 bits between dabs.
pub(crate) struct StrokeBuffer {
    pub original: Vec<Color32>,
    pub coverage: Vec<f32>,
    /// Selection coverage for this tile (0..=1 per pixel), computed on first
    /// use; the selection can't change during a stroke.
    pub selection: Option<Vec<f32>>,
    /// Pixels changed since the display last collected them, tile-local
    /// `[x0, y0, x1, y1)`; `None` if nothing changed.
    pub damage: Option<[usize; 4]>,
}

/// Tiles touched by the current stroke.
#[derive(Default)]
pub struct StrokeTiles {
    /// Tiles painted since the last redraw; drained every frame so redraw
    /// cost tracks new dabs, not the whole stroke's footprint.
    pub dirty: HashSet<(usize, usize)>,
    /// One buffer per tile this stroke has touched (also marks the tiles
    /// already snapshotted for undo).
    pub(crate) buffers: FxHashMap<(usize, usize), Mutex<StrokeBuffer>>,
}

/// Shared drawing dependencies for adding points to a stroke.
pub struct StrokeContext<'a> {
    pool: &'a ThreadPool,
    canvas: &'a Canvas,
    selection: Option<&'a SelectionManager>,
    undo_action: &'a mut UndoAction,
    stroke_tiles: &'a mut StrokeTiles,
}

impl<'a> StrokeContext<'a> {
    pub fn new(
        pool: &'a ThreadPool,
        canvas: &'a Canvas,
        selection: Option<&'a SelectionManager>,
        undo_action: &'a mut UndoAction,
        stroke_tiles: &'a mut StrokeTiles,
    ) -> Self {
        Self {
            pool,
            canvas,
            selection,
            undo_action,
            stroke_tiles,
        }
    }

    fn dabs(&mut self, brush: &mut Brush, centers: &[Vec2]) {
        brush.dabs(
            self.pool,
            self.canvas,
            self.selection,
            centers,
            self.undo_action,
            self.stroke_tiles,
        );
    }
}

/// Tracks per-stroke state like the last position and spacing accumulator.
pub struct StrokeState {
    pub last_pos: Option<Vec2>,
    stabilizer: Stabilizer,
    dist_until_next_blit: f32,
    /// Dabs generated by the current sample, with how far along the segment
    /// from the previous sample each lies (0..=1).
    pending: Vec<(Vec2, f32)>,
    /// Pressure of the previous sample; dabs between samples blend from it.
    last_pressure: Option<f32>,
    /// Dab positions of one pressure run, reused between samples.
    run: Vec<Vec2>,
}

impl StrokeState {
    /// Create an empty stroke state.
    pub fn new() -> Self {
        Self {
            last_pos: None,
            stabilizer: Stabilizer::default(),
            dist_until_next_blit: 0.0,
            pending: Vec::new(),
            last_pressure: None,
            run: Vec::new(),
        }
    }

    /// Add a new sample to the stroke, interpolating dabs based on spacing and
    /// jitter. `pressure` (0..=1, `1.0` for a mouse) drives whatever the
    /// brush maps it to: diameter (down to `pressure_min_size`), opacity,
    /// flow. In wash mode pressure-opacity goes to the dabs' strength instead
    /// of the stroke's opacity cap, which must stay fixed for a whole stroke.
    ///
    /// These are temporarily overwritten on `brush` for the duration of this
    /// call and restored before returning, including on panic (via
    /// `catch_unwind`) so a mid-call panic can never leave the brush's
    /// settings corrupted for later strokes.
    pub fn add_point(
        &mut self,
        brush: &mut Brush,
        raw_pos: Vec2,
        pressure: f32,
        context: &mut StrokeContext<'_>,
    ) {
        let o = &brush.brush_options;
        let original = (o.diameter, o.opacity, o.flow);
        let p = pressure.clamp(0.0, 1.0);
        let from = self.last_pressure.unwrap_or(p);

        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            // Spacing and jitter follow this sample's pressure.
            apply_pressure(brush, original, p);
            self.add_point_at_pressure(brush, raw_pos);
            // Pressure blends along the segment, so a slow pen (or a big
            // pressure change between samples) doesn't paint visible steps.
            // Dabs are painted in runs of equal (rounded) pressure.
            let pending = std::mem::take(&mut self.pending);
            let mut run = std::mem::take(&mut self.run);
            let mut level = None;
            for &(pos, t) in &pending {
                let q = pressure_level(from + (p - from) * t);
                if level != Some(q) {
                    if let Some(prev) = level
                        && !run.is_empty()
                    {
                        apply_pressure(brush, original, prev as f32 / PRESSURE_LEVELS);
                        context.dabs(brush, &run);
                        run.clear();
                    }
                    level = Some(q);
                }
                run.push(pos);
            }
            if let Some(last) = level
                && !run.is_empty()
            {
                apply_pressure(brush, original, last as f32 / PRESSURE_LEVELS);
                context.dabs(brush, &run);
            }
            run.clear();
            self.run = run;
            self.pending = pending;
            self.pending.clear();
        }));

        let o = &mut brush.brush_options;
        (o.diameter, o.opacity, o.flow) = original;
        self.last_pressure = Some(p);

        if let Err(payload) = result {
            std::panic::resume_unwind(payload);
        }
    }

    /// Queue the dabs for one sample into `self.pending`.
    fn add_point_at_pressure(&mut self, brush: &Brush, raw_pos: Vec2) {
        if brush.pixel_perfect {
            self.add_point_pixel_perfect(raw_pos);
            return;
        }

        let pos = self
            .stabilizer
            .step(&brush.stabilizer_settings(), self.last_pos, raw_pos);

        let spacing_dist = (brush.brush_options.spacing / 100.0) * brush.brush_options.diameter;
        let spacing_dist = spacing_dist.max(0.5); // Avoid infinite loops

        if let Some(prev) = self.last_pos {
            let delta = pos - prev;
            let length = delta.length();
            let mut dist_left = length;

            if dist_left == 0.0 {
                return;
            }

            let unit_step = delta / dist_left;
            let mut cur_pos = prev;

            while dist_left >= self.dist_until_next_blit {
                // Take a step to the next blit point.
                cur_pos += unit_step * self.dist_until_next_blit;
                dist_left -= self.dist_until_next_blit;

                // Blit.
                let mut p = cur_pos;
                if brush.jitter > 0.0 {
                    let mut rng = rand::rng();
                    let jitter_amount = (brush.jitter / 100.0) * brush.brush_options.diameter;
                    let jx = rng.random_range(-jitter_amount..=jitter_amount);
                    let jy = rng.random_range(-jitter_amount..=jitter_amount);
                    p.x += jx;
                    p.y += jy;
                }
                self.pending.push((p, 1.0 - dist_left / length));

                self.dist_until_next_blit = spacing_dist;
            }

            // Take the partial step to land at the sample.
            self.dist_until_next_blit -= dist_left;
        } else {
            // first point
            let mut p = pos;
            if brush.jitter > 0.0 {
                let mut rng = rand::rng();
                let jitter_amount = (brush.jitter / 100.0) * brush.brush_options.diameter;
                let jx = rng.random_range(-jitter_amount..=jitter_amount);
                let jy = rng.random_range(-jitter_amount..=jitter_amount);
                p.x += jx;
                p.y += jy;
            }
            self.pending.push((p, 1.0));
            self.dist_until_next_blit = spacing_dist;
        }

        self.last_pos = Some(pos);
    }

    /// Pixel-perfect Bresenham line stepping to avoid gaps when snapping to pixels.
    fn add_point_pixel_perfect(&mut self, pos: Vec2) {
        let x1 = pos.x.floor() as i32;
        let y1 = pos.y.floor() as i32;

        if let Some(prev) = self.last_pos {
            let x0 = prev.x.floor() as i32;
            let y0 = prev.y.floor() as i32;

            if x0 == x1 && y0 == y1 {
                return;
            }

            let dx = (x1 - x0).abs();
            let dy = -(y1 - y0).abs();
            let sx = if x0 < x1 { 1 } else { -1 };
            let sy = if y0 < y1 { 1 } else { -1 };
            let mut err = dx + dy;

            let mut x = x0;
            let mut y = y0;
            let steps = dx.max(-dy).max(1) as f32;

            loop {
                // Chebyshev distance walked, as a fraction of the line.
                let t = (x - x0).abs().max((y - y0).abs()) as f32 / steps;
                self.pending.push((
                    Vec2 {
                        x: x as f32 + 0.5,
                        y: y as f32 + 0.5,
                    },
                    t,
                ));

                if x == x1 && y == y1 {
                    break;
                }
                let e2 = 2 * err;
                if e2 >= dy {
                    err += dy;
                    x += sx;
                }
                if e2 <= dx {
                    err += dx;
                    y += sy;
                }
            }
        } else {
            self.pending.push((
                Vec2 {
                    x: x1 as f32 + 0.5,
                    y: y1 as f32 + 0.5,
                },
                1.0,
            ));
        }
        self.last_pos = Some(pos);
    }
}

/// Pressure steps dabs are grouped by; finer than any visible change.
const PRESSURE_LEVELS: f32 = 64.0;

fn pressure_level(p: f32) -> u32 {
    (p.clamp(0.0, 1.0) * PRESSURE_LEVELS).round() as u32
}

/// Set what pressure `p` drives on the brush, from its unpressured
/// `(diameter, opacity, flow)`. In wash mode pressure-opacity goes to the
/// dabs' strength instead of the stroke's opacity cap, which must stay fixed
/// for a whole stroke.
fn apply_pressure(brush: &mut Brush, (diameter, opacity, flow): (f32, f32, f32), p: f32) {
    let o = &mut brush.brush_options;
    (o.diameter, o.opacity, o.flow) = (diameter, opacity, flow);
    if o.pressure_size {
        let factor = o.pressure_min_size + (1.0 - o.pressure_min_size) * p;
        o.diameter = (diameter * factor).max(1.0);
    }
    if o.pressure_opacity {
        if o.painting_mode == crate::brush_engine::brush_options::PaintingMode::Wash {
            o.flow *= p;
        } else {
            o.opacity *= p;
        }
    }
    if o.pressure_flow {
        o.flow *= p;
    }
}

impl Default for StrokeState {
    fn default() -> Self {
        Self::new()
    }
}
